//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesSalePage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Admin
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AdminID { get; set; }
        [Required(ErrorMessage = "This can not be null")]
        [Display(Name = "Account")]
        [MaxLength(20, ErrorMessage = "Length is over 20. Try again")]
        public string AdminName { get; set; }
        [Required(ErrorMessage = "This can not be null")]
        [Display(Name = "Full Name")]
        [MaxLength(100, ErrorMessage = "Length is over 100. Try again")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "This can not be null")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [MinLength(1, ErrorMessage ="Length is below 1. Try again")]
        [MaxLength(20, ErrorMessage = "Length is over 20. Try again")]
        public string AdminPassword { get; set; }
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }
        [NotMapped] // not create corresponding columns in the database
        [Required(ErrorMessage = "This can not be null")]
        [Compare("AdminPassword", ErrorMessage = "Password is incorrect")]
        [Display(Name = "Confirm password")]
        [DataType(DataType.Password)]
        public string ConfirmPass { get; set; }
    }
}
