//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesSalePage.Models
{
<<<<<<< HEAD
<<<<<<< Updated upstream
    public class Cart
=======
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cart
>>>>>>> Test
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CartID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }

<<<<<<< Updated upstream
<<<<<<< HEAD
        public int OrderID { get; set; } // Foreign Key
=======
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cart
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CartID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }

=======
>>>>>>> Test
=======
>>>>>>> Stashed changes
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
